/* Ethno-Musicology: router and views. Content comes from window.MUSICOLOGY
   (generated by tools/build_content.py). Vanilla JS, hash routing so the app
   works when served statically or embedded in an iframe. */
(function () {
  'use strict';
  var D = window.MUSICOLOGY, view = document.getElementById('view');
  var CUL = {}, FAC = {}, ENT = D.entries;
  D.cultures.forEach(function (c) { CUL[c.id] = c; });
  D.facets.forEach(function (f) { FAC[f.id] = f; });
  var ids = Object.keys(ENT);

  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); }
  function col(id) { return (CUL[id] || {}).color || '#b8863b'; }
  function cdot(id) { return '<i class="dot" style="background:' + col(id) + '"></i>'; }
  function prim(eid) { return ENT[eid].cultures[0]; }
  function href(eid) { return '#/e/' + eid; }

  function card(eid, extra) {
    var e = ENT[eid], c = e.cultures[0];
    var names = e.cultures.map(function (x) { return CUL[x].name; }).join(' · ');
    return '<a class="card" data-cultures="' + e.cultures.join(' ') + '" href="' + href(eid) + '" style="border-left-color:' + col(c) + '">' +
      '<div class="meta">' + cdot(c) + esc(names) + '</div><h3>' + esc(e.title) + '</h3><p>' + esc(e.summary) + '</p>' + (extra ? '<p style="margin-top:6px;color:#7a4f17"><em>' + esc(extra) + '</em></p>' : '') + '</a>';
  }

  function entriesFor(facet, section) {
    return ids.filter(function (i) { var f = ENT[i].facets[facet]; return f && (!section || f.indexOf(section) >= 0); });
  }
  function facetCount(f) { return entriesFor(f).length; }
  function cultureEntries(cid) { return ids.filter(function (i) { return ENT[i].cultures.indexOf(cid) >= 0; }); }
  function sectionOf(eid) {
    for (var f in ENT[eid].facets) { var s = ENT[eid].facets[f][0]; var sec = D.sections[f].filter(function (x) { return x.id === s; })[0]; return { facet: f, section: sec }; }
    return null;
  }

  /* ---------------- views ---------------- */
  function home() {
    var nThreads = D.threads.length, nLinks = 0, cross = 0;
    ids.forEach(function (i) { nLinks += ENT[i].out.length; });
    Object.keys(D.pairs).forEach(function (k) { cross += D.pairs[k].length; });
    var html = '<div class="hero"><p class="eyebrow">An atlas of musical thought</p>' +
      '<h1>How the world builds <em>melody</em>, <em>harmony</em> and <em>rhythm</em></h1>' +
      '<p class="lede">' + ids.length + ' deeply cross-linked entries across ' + (D.cultures.length - 1) + ' traditions. Follow one thread from culture to culture, or dive into a single tradition and read its scales, chords and cycles on their own terms. Every comparison says what is shared and what is not.</p></div>' +
      '<div class="portals">' + D.facets.map(function (f) {
        var secs = D.sections[f.id].length;
        return '<a class="portal" href="#/facet/' + f.id + '" style="border-top-color:' + ({ melody: '#d1a437', harmony: '#6f93ab', rhythm: '#c9483a' })[f.id] + '"><h2>' + f.name + '</h2><p>' + esc(f.blurb) + '</p><span class="count">' + facetCount(f.id) + ' entries · ' + secs + ' themes →</span></a>';
      }).join('') + '</div>' +
      '<div class="sec"><h2>Two ways to read</h2><div class="two-ways">' +
      '<div class="way"><h3>Across cultures, by theme</h3><p>Pick Melody and learn how scales are constructed worldwide: tuning, building blocks, parent-scale systems, what makes a mode a mode, five-note worlds. The same pages show every culture side by side.</p></div>' +
      '<div class="way"><h3>One culture, all three facets</h3><p>Pick a tradition and read its melody, harmony and rhythm together, with a panel that calls out every connection to other cultures.</p></div></div></div>' +
      '<div class="sec"><h2>Cultures</h2><div class="culture-grid">' + D.cultures.map(function (c) {
        var n = cultureEntries(c.id).length;
        return '<a class="culture-card" href="#/culture/' + c.id + '" style="border-top-color:' + c.color + '"><h3>' + esc(c.name) + '</h3><div class="rg">' + esc(c.region) + '</div><div class="ct">' + n + ' entr' + (n === 1 ? 'y' : 'ies') + '</div></a>';
      }).join('') + '</div></div>' +
      '<div class="sec"><h2>Threads that cross cultures</h2><p class="intro">Short guided paths through the entries, each following one idea as it turns up in different places.</p><div class="grid">' +
      D.threads.slice(0, 6).map(function (t) { return '<a class="card dark" href="#/thread/' + t.id + '" style="border-left-color:#d1a437"><div class="meta">' + t.steps.length + ' entries · ' + t.kind + '</div><h3>' + esc(t.title) + '</h3><p>' + esc(t.intro.split('. ')[0]) + '.</p></a>'; }).join('') +
      '</div><p style="margin-top:12px"><a href="#/threads">All ' + nThreads + ' threads →</a></p></div>' +
      '<div class="sec"><h2>Labs</h2><div class="grid">' +
      '<a class="card dark" href="#/lab/scales" style="border-left-color:#d1a437"><h3>Scale Lab</h3><p>Overlay scales from different traditions on one cents ruler and hear them against a drone.</p></a>' +
      '<a class="card dark" href="#/lab/atlas" style="border-left-color:#6f93ab"><h3>Interval Atlas</h3><p>Every named interval size across the entries, from the koma to the fifth.</p></a>' +
      '<a class="card dark" href="#/lab/cycles" style="border-left-color:#c9483a"><h3>Cycle Lab</h3><p>Rhythmic cycles as circles; play up to three at once on a shared cycle length.</p></a>' +
      '<a class="card dark" href="#/connections" style="border-left-color:#4f9d8f"><h3>Connections map</h3><p>' + cross + ' links between entries of different cultures, by culture pair.</p></a></div></div>';
    return { html: html, title: 'Ethno-Musicology' };
  }

  function facetView(fid) {
    var f = FAC[fid]; if (!f) return notFound();
    var present = [];
    entriesFor(fid).forEach(function (i) { ENT[i].cultures.forEach(function (c) { if (present.indexOf(c) < 0) present.push(c); }); });
    var html = '<p class="eyebrow">Explore by facet</p><h1 class="page">' + f.name + '</h1><p class="lede">' + esc(f.blurb) + '</p>' +
      '<div class="filterbar" id="cf"><span style="font-size:.8rem;color:var(--muted)">Highlight a culture:</span>' +
      D.cultures.filter(function (c) { return present.indexOf(c.id) >= 0; }).map(function (c) { return '<button data-c="' + c.id + '">' + cdot(c.id) + esc(c.name) + '</button>'; }).join('') + '</div>';
    D.sections[fid].forEach(function (s) {
      var list = entriesFor(fid, s.id);
      html += '<section class="sec"><h2>' + esc(s.name) + '</h2><p class="intro">' + esc(s.intro) + '</p>' +
        (list.length ? '<div class="grid">' + list.map(function (i) { return card(i); }).join('') + '</div>' : '<div class="empty">Nothing recorded here yet.</div>') + '</section>';
    });
    if (fid === 'harmony') html += '<section class="sec"><div class="empty">Harmony in the chord-and-progression sense is recorded here for Western classical and jazz. Other traditions in this atlas organize pitch with drones, modes and melody instead; where they touch harmony (the Sa-Pa drone, the root-fifth anchor) it is shown above. Polyphonic and heterophonic traditions are not covered yet.</div></section>';
    return { html: html, title: f.name + ' — Ethno-Musicology', after: function () {
      var bar = document.getElementById('cf'), cur = null;
      bar.addEventListener('click', function (e) {
        var b = e.target.closest('button'); if (!b) return;
        cur = cur === b.dataset.c ? null : b.dataset.c;
        bar.querySelectorAll('button').forEach(function (x) { x.classList.toggle('on', x.dataset.c === cur); });
        view.querySelectorAll('.card').forEach(function (cd) { cd.classList.toggle('dim', !!cur && cd.dataset.cultures.split(' ').indexOf(cur) < 0); });
      });
    } };
  }

  function culturesView() {
    var html = '<p class="eyebrow">Explore by culture</p><h1 class="page">Cultures</h1><p class="lede">Pick a tradition to read its melody, harmony and rhythm together, with every link to other cultures called out.</p><div class="culture-grid">' +
      D.cultures.map(function (c) {
        var ce = cultureEntries(c.id), fc = D.facets.map(function (f) { return f.name[0] + ' ' + ce.filter(function (i) { return ENT[i].facets[f.id]; }).length; }).join(' · ');
        return '<a class="culture-card" href="#/culture/' + c.id + '" style="border-top-color:' + c.color + '"><h3>' + esc(c.name) + '</h3><div class="rg">' + esc(c.region) + '</div><p style="margin:6px 0 0;font-size:.8rem;color:#c9bfa6">' + esc(c.blurb) + '</p><div class="ct">' + fc + '</div></a>';
      }).join('') + '</div>';
    return { html: html, title: 'Cultures — Ethno-Musicology' };
  }

  function cultureView(cid) {
    var c = CUL[cid]; if (!c) return notFound();
    var ce = cultureEntries(cid);
    var html = '<div class="crumbs"><a href="#/cultures">Cultures</a> › ' + esc(c.name) + '</div><p class="eyebrow">' + esc(c.region) + '</p><h1 class="page">' + cdot(cid) + esc(c.name) + '</h1><p class="lede">' + esc(c.blurb) + '</p>';
    D.facets.forEach(function (f) {
      var list = ce.filter(function (i) { return ENT[i].facets[f.id]; });
      html += '<section class="sec"><h2>' + f.name + '</h2>' + (list.length ? '<div class="grid">' + list.map(function (i) { return card(i); }).join('') + '</div>' : '<div class="empty">Not yet covered for this tradition. The atlas grows as new entries are added.</div>') + '</section>';
    });
    // connections out
    var rows = [];
    Object.keys(D.pairs).forEach(function (k) {
      var p = k.split('|'); if (p.indexOf(cid) < 0) return;
      var other = p[0] === cid ? p[1] : p[0];
      rows.push({ other: other, key: k, n: D.pairs[k].length });
    });
    rows.sort(function (a, b) { return b.n - a.n; });
    html += '<section class="sec"><h2>Connections to other cultures</h2><p class="intro">Each count is the number of entry-to-entry links between this culture’s entries and the other’s. Open a pair to read the sentences where the connection is made.</p>' +
      (rows.length ? '<div class="chips">' + rows.map(function (r) { return '<a class="chip" href="#/connections/' + r.key + '">' + cdot(r.other) + esc(CUL[r.other].name) + ' · ' + r.n + '</a>'; }).join('') + '</div>' : '<div class="empty">No cross-culture links recorded yet.</div>') + '</section>';
    return { html: html, title: c.name + ' — Ethno-Musicology' };
  }

  function sidebarConnections(eid) {
    var e = ENT[eid], seen = {}, groups = {};
    function add(to, ctx, dir) {
      if (!ENT[to]) return;
      var k = to + dir; if (seen[k]) return; seen[k] = 1;
      var cu = prim(to); (groups[cu] = groups[cu] || []).push({ to: to, ctx: ctx, dir: dir });
    }
    e.out.forEach(function (o) { add(o.to, o.ctx, 'cites'); });
    e.back.forEach(function (b) { add(b.from, b.ctx, 'cited by'); });
    var keys = Object.keys(groups).sort(function (a, b) {
      var s = prim(eid); return (b === s) - (a === s) || groups[b].length - groups[a].length;
    });
    if (!keys.length) return '<div class="box"><h3>Connections</h3><p class="tiny">No links recorded yet.</p></div>';
    var html = '<div class="box"><h3>Connections</h3><p class="tiny">Entries this one cites, and entries that cite it, grouped by culture.</p>';
    keys.forEach(function (k) {
      html += '<div style="margin-top:8px;font-size:.78rem;color:var(--brass-light)">' + cdot(k) + esc(CUL[k].name) + (k === prim(eid) ? ' (same culture)' : '') + '</div>';
      groups[k].forEach(function (g) {
        html += '<a class="conn" href="' + href(g.to) + '"><div class="ct">' + esc(ENT[g.to].title) + '</div><div class="cc">' + g.dir + '</div><div class="cx">' + esc(g.ctx) + '</div></a>';
      });
    });
    return html + '</div>';
  }

  function entryView(eid) {
    var e = ENT[eid]; if (!e) return notFound();
    var so = sectionOf(eid), c = e.cultures[0];
    var crumbs = '<div class="crumbs">' + (so ? '<a href="#/facet/' + so.facet + '">' + FAC[so.facet].name + '</a> › ' + esc(so.section.name) + ' › ' : '') +
      e.cultures.map(function (x) { return '<a href="#/culture/' + x + '">' + esc(CUL[x].name) + '</a>'; }).join(' · ') + '</div>';
    var mins = Math.max(1, Math.round(e.words / 210));
    var inThreads = D.threads.filter(function (t) { return t.steps.some(function (s) { return s.id === eid; }); });
    var pager = '';
    if (so) {
      var list = entriesFor(so.facet, so.section.id), i = list.indexOf(eid);
      var prev = list[i - 1], next = list[i + 1];
      pager = '<div class="pager">' + (prev ? '<a class="card dark" href="' + href(prev) + '"><div class="meta">← previous in this theme</div><h3>' + esc(ENT[prev].title) + '</h3></a>' : '') +
        (next ? '<a class="card dark" href="' + href(next) + '"><div class="meta">next in this theme →</div><h3>' + esc(ENT[next].title) + '</h3></a>' : '') + '</div>';
    }
    var html = crumbs + '<div class="entry-head"><h1>' + esc(e.title) + '</h1><p class="sum">' + esc(e.summary) + '</p><div class="sub">' +
      e.cultures.map(function (x) { return '<span class="chip">' + cdot(x) + esc(CUL[x].name) + '</span>'; }).join('') +
      Object.keys(e.facets).map(function (f) { return '<a class="chip" href="#/facet/' + f + '">' + FAC[f].name + '</a>'; }).join('') +
      '<span>' + mins + ' min read</span></div></div>' +
      '<div class="layout"><div><article class="article" id="art">' + e.html + '</article>' + pager + '</div><aside class="side"><div class="sticky">' +
      sidebarConnections(eid) +
      (inThreads.length ? '<div class="box"><h3>Part of threads</h3><div class="chips">' + inThreads.map(function (t) { return '<a class="chip" href="#/thread/' + t.id + '">' + esc(t.title) + '</a>'; }).join('') + '</div></div>' : '') +
      '</div></aside></div>';
    return { html: html, title: e.title + ' — Ethno-Musicology', after: function () {
      view.querySelectorAll('#art a.xref').forEach(function (a) {
        var t = decodeURIComponent(a.getAttribute('href').slice(4));
        if (ENT[t]) { a.style.setProperty('--xc', col(prim(t))); a.title = CUL[prim(t)].name + ': ' + ENT[t].title; }
      });
    } };
  }

  function threadsView() {
    var html = '<p class="eyebrow">Guided paths</p><h1 class="page">Threads</h1><p class="lede">Each thread follows one idea as it turns up in different traditions, in the order that makes it easiest to follow.</p><div class="grid">' +
      D.threads.map(function (t) { return '<a class="card dark" href="#/thread/' + t.id + '" style="border-left-color:#d1a437"><div class="meta">' + t.steps.length + ' entries · ' + t.kind + '</div><h3>' + esc(t.title) + '</h3><p>' + esc(t.intro.split('. ')[0]) + '.</p></a>'; }).join('') + '</div>';
    return { html: html, title: 'Threads — Ethno-Musicology' };
  }
  function threadView(tid) {
    var t = D.threads.filter(function (x) { return x.id === tid; })[0]; if (!t) return notFound();
    var html = '<div class="crumbs"><a href="#/threads">Threads</a></div><p class="eyebrow">' + t.kind + ' · ' + t.steps.length + ' entries</p><h1 class="page">' + esc(t.title) + '</h1><p class="lede">' + esc(t.intro) + '</p><ol class="thread-steps">' +
      t.steps.map(function (s) { return '<li><div>' + card(s.id, s.why) + '</div></li>'; }).join('') + '</ol>';
    return { html: html, title: t.title + ' — Ethno-Musicology' };
  }

  function connectionsView(pairKey) {
    var cs = D.cultures, max = 0, m = {};
    Object.keys(D.pairs).forEach(function (k) { m[k] = D.pairs[k].length; max = Math.max(max, m[k]); });
    var html = '<p class="eyebrow">How the traditions connect</p><h1 class="page">Connections</h1><p class="lede">Each cell counts links between entries of two cultures. A link is a place where one entry cites another to make a comparison, a contrast, or a correction. Click a cell to read the sentences.</p>' +
      '<div class="matrix-wrap"><table class="matrix"><tr><th></th>' + cs.map(function (c) { return '<th class="col">' + esc(c.name) + '</th>'; }).join('') + '</tr>';
    cs.forEach(function (a) {
      html += '<tr><th class="row">' + esc(a.name) + '</th>';
      cs.forEach(function (b) {
        if (a.id === b.id) { html += '<td class="diag"></td>'; return; }
        var k = [a.id, b.id].sort().join('|'), n = m[k] || 0;
        var bg = n ? 'background:rgba(209,164,55,' + (0.25 + 0.75 * n / max).toFixed(2) + ')' : '';
        html += '<td class="' + (n ? 'has' : '') + (k === pairKey ? ' sel' : '') + '" style="' + bg + (k === pairKey ? ';outline:2px solid #fff' : '') + '"' + (n ? ' data-k="' + k + '" title="' + esc(a.name + ' ↔ ' + b.name) + '"' : '') + '>' + (n || '') + '</td>';
      });
      html += '</tr>';
    });
    html += '</table></div><div id="pairs" class="pairs">' + pairDetail(pairKey) + '</div>';
    // most-connected entries
    var rank = ids.map(function (i) {
      var n = 0; ENT[i].out.concat(ENT[i].back.map(function (b) { return { to: b.from }; })).forEach(function (o) { if (ENT[o.to] && prim(o.to) !== prim(i)) n++; });
      return { i: i, n: n };
    }).sort(function (a, b) { return b.n - a.n; }).slice(0, 8);
    html += '<section class="sec"><h2>Most connected entries</h2><p class="intro">Entries with the most links to other cultures: the best starting points for comparison.</p><div class="grid">' +
      rank.map(function (r) { return card(r.i, r.n + ' cross-culture links'); }).join('') + '</div></section>';
    return { html: html, title: 'Connections — Ethno-Musicology', after: function () {
      view.querySelector('.matrix').addEventListener('click', function (e) {
        var td = e.target.closest('td.has'); if (!td) return;
        location.hash = '#/connections/' + td.dataset.k;
      });
    } };
  }
  function pairDetail(k) {
    if (!k || !D.pairs[k]) return '<div class="empty">Select a cell above to read how two traditions connect.</div>';
    var p = k.split('|');
    return '<h2 style="margin:0 0 6px">' + cdot(p[0]) + esc(CUL[p[0]].name) + ' ↔ ' + cdot(p[1]) + esc(CUL[p[1]].name) + '</h2>' +
      D.pairs[k].map(function (x) {
        return '<div class="pair-item"><div class="ph"><a href="' + href(x.from) + '">' + esc(ENT[x.from].title) + '</a> → <a href="' + href(x.to) + '">' + esc(ENT[x.to].title) + '</a></div><p>' + esc(x.ctx) + '</p></div>';
      }).join('');
  }

  function labView(which, qs) {
    return { html: '<div id="labroot"></div>', title: 'Labs — Ethno-Musicology', after: function () {
      var r = document.getElementById('labroot');
      (window.Labs[which] || window.Labs.scales)(r, qs);
    } };
  }

  function notFound() { return { html: '<h1 class="page">Not found</h1><p class="lede">That page is not in the atlas. <a href="#/">Back to the start.</a></p>', title: 'Not found — Ethno-Musicology' }; }

  /* ---------------- router ---------------- */
  function parseQS(s) { var o = {}; (s || '').split('&').forEach(function (p) { var i = p.indexOf('='); if (i > 0) o[p.slice(0, i)] = decodeURIComponent(p.slice(i + 1)); }); return o; }
  function route() {
    window.Labs.stop();
    var h = location.hash || '#/', q = '', qi = h.indexOf('?');
    if (qi > 0) { q = h.slice(qi + 1); h = h.slice(0, qi); }
    var parts = h.replace(/^#\//, '').split('/'), r;
    switch (parts[0]) {
      case '': r = home(); break;
      case 'facet': r = facetView(parts[1]); break;
      case 'cultures': r = culturesView(); break;
      case 'culture': r = cultureView(parts[1]); break;
      case 'e': r = entryView(decodeURIComponent(parts.slice(1).join('/'))); break;
      case 'threads': r = threadsView(); break;
      case 'thread': r = threadView(parts[1]); break;
      case 'connections': r = connectionsView(parts[1]); break;
      case 'lab': r = labView(parts[1] || 'scales', parseQS(q)); break;
      default: r = notFound();
    }
    view.innerHTML = r.html;
    document.title = r.title;
    if (r.after) r.after();
    document.querySelectorAll('#nav a').forEach(function (a) {
      var n = a.dataset.nav, on = (n === parts[0]) || (n === 'facet/' + parts[1] && parts[0] === 'facet') ||
        (n === 'culture' && (parts[0] === 'cultures' || parts[0] === 'culture')) || (n === 'thread' && parts[0] === 'threads') ||
        (n === 'lab' && parts[0] === 'lab') || (n === 'connections' && parts[0] === 'connections');
      a.classList.toggle('on', !!on);
    });
    if (!window.__first) window.scrollTo(0, 0);
    window.__first = false;
    var rs = document.getElementById('results'); rs.hidden = true;
  }
  window.__first = true;
  window.addEventListener('hashchange', route);

  /* ---------------- search ---------------- */
  var idx = null;
  function buildIdx() {
    idx = ids.map(function (i) {
      var t = ENT[i].html.replace(/<[^>]+>/g, ' ').replace(/&gt;/g, '>').replace(/&lt;/g, '<').replace(/&amp;/g, '&').replace(/\s+/g, ' ');
      return { id: i, title: ENT[i].title.toLowerCase(), sum: ENT[i].summary.toLowerCase(), body: t, low: t.toLowerCase() };
    });
  }
  var q = document.getElementById('q'), rs = document.getElementById('results');
  function doSearch() {
    var s = q.value.trim().toLowerCase();
    if (s.length < 2) { rs.hidden = true; return; }
    if (!idx) buildIdx();
    var toks = s.split(/\s+/), out = [];
    idx.forEach(function (x) {
      var sc = 0, ok = true, first = -1;
      toks.forEach(function (t) {
        var inT = x.title.indexOf(t) >= 0, inS = x.sum.indexOf(t) >= 0, p = x.low.indexOf(t);
        if (!inT && !inS && p < 0) ok = false;
        sc += (inT ? 6 : 0) + (inS ? 3 : 0) + (p >= 0 ? 1 : 0);
        if (p >= 0 && first < 0) first = p;
      });
      if (ok) out.push({ x: x, sc: sc, first: first });
    });
    out.sort(function (a, b) { return b.sc - a.sc; });
    rs.hidden = false;
    rs.innerHTML = out.length ? out.slice(0, 12).map(function (o) {
      var sn = o.first >= 0 ? '…' + o.x.body.substr(Math.max(0, o.first - 50), 130) + '…' : ENT[o.x.id].summary;
      return '<a href="' + href(o.x.id) + '"><div class="rt">' + cdot(prim(o.x.id)) + esc(ENT[o.x.id].title) + '</div><div class="rs">' + esc(sn) + '</div></a>';
    }).join('') : '<div class="none">No entries match “' + esc(q.value) + '”.</div>';
  }
  q.addEventListener('input', doSearch);
  q.addEventListener('keydown', function (e) {
    if (e.key === 'Escape') { rs.hidden = true; q.blur(); }
    if (e.key === 'Enter') { var a = rs.querySelector('a'); if (a) { location.hash = a.getAttribute('href'); q.value = ''; rs.hidden = true; } }
  });
  document.addEventListener('click', function (e) { if (!e.target.closest('.search')) rs.hidden = true; });
  rs.addEventListener('click', function () { q.value = ''; });

  var nLinks = 0; ids.forEach(function (i) { nLinks += ENT[i].out.length; });
  document.getElementById('stats').textContent = ids.length + ' entries, ' + nLinks + ' links.';
  route();
})();
