/* Musicology labs: Scale Lab, Interval Atlas, Cycle Lab.
   All data comes from window.MUSICOLOGY (generated by tools/build_content.py
   from the knowledge base); this file only draws and sounds it. */
(function () {
  'use strict';
  var D = window.MUSICOLOGY;
  var CUL = {};
  D.cultures.forEach(function (c) { CUL[c.id] = c; });

  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); }
  function col(id) { return (CUL[id] || {}).color || '#b8863b'; }
  function cname(id) { return (CUL[id] || {}).name || id; }
  function link(eid, text) { return '<a href="#/e/' + eid + '">' + esc(text) + '</a>'; }
  function entTitle(eid) { return D.entries[eid] ? D.entries[eid].title : eid; }
  function nearest12(c) { var n = Math.round(c / 100) * 100; return { note: n, dev: c - n }; }
  function fmt(c) { return (Math.round(c * 10) / 10).toFixed(1); }
  function fmtDev(d) { var r = Math.round(d * 10) / 10; return (r > 0 ? '+' : '') + r.toFixed(1); }

  /* ---------------- audio ---------------- */
  var ctx = null, bus = null, timers = [], raf = 0, onStop = null;
  function audio() {
    if (!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)();
    if (ctx.state === 'suspended') ctx.resume();
    return ctx;
  }
  function newBus() {
    var c = audio();
    bus = c.createGain();
    bus.gain.value = 0.9;
    bus.connect(c.destination);
    return bus;
  }
  function stopAll() {
    timers.forEach(function (t) { clearTimeout(t); clearInterval(t); });
    timers = [];
    if (raf) { cancelAnimationFrame(raf); raf = 0; }
    if (bus && ctx) {
      var b = bus; bus = null;
      try { b.gain.setTargetAtTime(0, ctx.currentTime, 0.03); } catch (e) {}
      setTimeout(function () { try { b.disconnect(); } catch (e) {} }, 200);
    }
    if (onStop) { var f = onStop; onStop = null; f(); }
  }
  function tone(freq, t, dur, type, gain, dest) {
    var c = ctx, o = c.createOscillator(), g = c.createGain();
    o.type = type || 'triangle';
    o.frequency.setValueAtTime(freq, t);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(gain || 0.25, t + 0.015);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    o.connect(g); g.connect(dest || bus);
    o.start(t); o.stop(t + dur + 0.05);
  }
  function noiseBurst(t, dur, gain, f) {
    var c = ctx, n = Math.max(1, Math.floor(c.sampleRate * dur)), buf = c.createBuffer(1, n, c.sampleRate), d = buf.getChannelData(0);
    for (var i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);
    var s = c.createBufferSource(), bp = c.createBiquadFilter(), g = c.createGain();
    s.buffer = buf; bp.type = 'bandpass'; bp.frequency.value = f || 1800; bp.Q.value = 0.8;
    g.gain.value = gain || 0.3;
    s.connect(bp); bp.connect(g); g.connect(bus); s.start(t);
  }
  function thump(t) {
    var c = ctx, o = c.createOscillator(), g = c.createGain();
    o.type = 'sine';
    o.frequency.setValueAtTime(150, t); o.frequency.exponentialRampToValueAtTime(70, t + 0.12);
    g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(0.7, t + 0.01); g.gain.exponentialRampToValueAtTime(0.0001, t + 0.3);
    o.connect(g); g.connect(bus); o.start(t); o.stop(t + 0.35);
  }
  var F0 = 220;
  function freq(c) { return F0 * Math.pow(2, c / 1200); }

  /* ---------------- tooltip ---------------- */
  var tip;
  function tipEl() {
    if (!tip) { tip = document.createElement('div'); tip.className = 'tip'; document.body.appendChild(tip); }
    return tip;
  }
  function tipShow(ev, html) { var t = tipEl(); t.innerHTML = html; t.style.display = 'block'; tipMove(ev); }
  function tipMove(ev) { var t = tipEl(); t.style.left = Math.min(window.innerWidth - 270, ev.clientX + 14) + 'px'; t.style.top = (ev.clientY + 16) + 'px'; }
  function tipHide() { if (tip) tip.style.display = 'none'; }
  function bindTips(root) {
    root.querySelectorAll('[data-tip]').forEach(function (el) {
      el.addEventListener('mouseenter', function (e) { tipShow(e, el.getAttribute('data-tip')); });
      el.addEventListener('mousemove', tipMove);
      el.addEventListener('mouseleave', tipHide);
    });
  }

  /* ================= SCALE LAB ================= */
  var selScales = null;

  function scalesView(root, qs) {
    var all = D.scales, byId = {};
    all.forEach(function (s) { byId[s.id] = s; });
    if (qs && qs.s) selScales = qs.s.split(',').filter(function (x) { return byId[x]; });
    if (!selScales) selScales = ['gong-pyth', 'major-pent', 'yo', 'slendro'];

    var groups = [];
    all.forEach(function (s) { if (groups.indexOf(s.group) < 0) groups.push(s.group); });

    var pick = groups.map(function (g) {
      return '<h3>' + esc(g) + '</h3>' + all.filter(function (s) { return s.group === g; }).map(function (s) {
        return '<label><input type="checkbox" value="' + s.id + '"' + (selScales.indexOf(s.id) >= 0 ? ' checked' : '') + '>' +
          '<span><i class="dot" style="background:' + col(s.culture) + '"></i>' + esc(s.name) + '</span></label>';
      }).join('');
    }).join('');

    root.innerHTML =
      '<div class="subnav">' + subnav('scales') + '</div>' +
      '<p class="eyebrow">Melody · Lab</p><h1 class="page">Scale Lab</h1>' +
      '<p class="lede">Put scales from different traditions on the same cents ruler and listen to them against a drone. Grid lines are the 12-tone equal-tempered positions, so you can see where a tuning departs from the piano. Every scale links to the entry its numbers come from.</p>' +
      '<div class="lab"><div class="pick" id="pick">' + pick + '</div><div class="stage" id="stage"></div></div>';

    var stage = root.querySelector('#stage');

    function render() {
      var chosen = selScales.map(function (id) { return byId[id]; }).filter(Boolean);
      if (!chosen.length) { stage.innerHTML = '<p class="hint">Pick one or more scales on the left.</p>'; return; }
      var maxSpan = Math.max.apply(null, chosen.map(function (s) { return s.span; }));
      var range = maxSpan > 800 ? 1200 : Math.ceil(maxSpan / 100) * 100;
      var W = 1000, X = function (c) { return 12 + (c / range) * (W - 24); };
      var html = '<h2>' + chosen.length + ' selected</h2><p class="hint">Hover a note for its cents and its distance from the nearest piano note. Tonic is always at 0.</p>' +
        '<div class="btnrow"><button class="btn" data-act="all">▶ Play all, one after another</button><button class="btn ghost" data-act="stop">Stop</button>' +
        '<label style="font-size:.85rem"><input type="checkbox" id="dr" checked> sound a drone</label></div>';
      chosen.forEach(function (s) {
        var svg = '<svg viewBox="0 0 ' + W + ' 46" aria-label="' + esc(s.name) + ' on a cents ruler">';
        for (var g = 0; g <= range; g += 100) {
          svg += '<line x1="' + X(g) + '" x2="' + X(g) + '" y1="4" y2="42" stroke="' + (g % 1200 === 0 ? '#8a7a5a' : '#cdbf9f') + '" stroke-width="' + (g % 300 === 0 ? 1.4 : 0.8) + '"/>';
        }
        svg += '<line x1="12" x2="' + (W - 12) + '" y1="23" y2="23" stroke="#cdbf9f" stroke-width="1"/>';
        var pos = s.pos.slice();
        if (Math.abs(s.span - pos[pos.length - 1]) > 1) pos.push(s.span);
        pos.forEach(function (p, i) {
          var n = nearest12(p), x = X(p), isEnd = i === pos.length - 1 && i > 0;
          var tipHtml = esc(s.name) + '<br>degree ' + (i + 1) + (isEnd ? ' (span end)' : '') + ': <b>' + fmt(p) + '</b> cents<br>nearest 12-tone note ' + n.note + ' (' + fmtDev(n.dev) + ')';
          if (Math.abs(n.dev) > 1.5) svg += '<line x1="' + X(n.note) + '" x2="' + x + '" y1="23" y2="23" stroke="#c9483a" stroke-width="3" stroke-linecap="round" opacity=".7"/>';
          svg += '<circle cx="' + x + '" cy="23" r="' + (isEnd ? 5 : 8) + '" fill="' + (isEnd ? 'none' : col(s.culture)) + '" stroke="' + col(s.culture) + '" stroke-width="2.5" data-tip="' + tipHtml.replace(/"/g, '&quot;') + '"/>';
        });
        svg += '</svg>';
        html += '<div class="rowscale"><div class="rn"><i class="dot" style="background:' + col(s.culture) + '"></i>' + esc(s.name) +
          ' <button class="btn ghost" data-play="' + s.id + '" style="padding:2px 12px">▶</button>' +
          ' <span style="font-weight:400;font-size:.78rem">' + link(s.entry, 'source entry') + '</span></div>' +
          (s.aka.length ? '<div class="aka">also: ' + s.aka.map(esc).join(' · ') + '</div>' : '') + svg +
          (s.note ? '<div class="note">' + esc(s.note) + '</div>' : '') + '</div>';
      });
      // axis legend
      html += '<div class="legend"><span>Ruler: 0 to ' + range + ' cents. Red segment = distance from the nearest piano note.</span></div>';
      // data table
      chosen.forEach(function (s) {
        var pos = s.pos;
        html += '<table class="dt"><tr><th>' + esc(s.name) + '</th>' + pos.map(function (_, i) { return '<th>' + (i + 1) + '</th>'; }).join('') + '</tr>' +
          '<tr><td>cents</td>' + pos.map(function (p) { return '<td>' + fmt(p) + '</td>'; }).join('') + '</tr>' +
          '<tr><td>vs piano</td>' + pos.map(function (p) { return '<td>' + fmtDev(nearest12(p).dev) + '</td>'; }).join('') + '</tr></table>';
      });
      if (chosen.length === 2 && chosen[0].pos.length === chosen[1].pos.length) {
        var a = chosen[0], b = chosen[1];
        html += '<h3 style="font-family:Inter,sans-serif;font-size:.9rem;margin:16px 0 4px">Degree by degree: ' + esc(b.name) + ' minus ' + esc(a.name) + '</h3><table class="dt"><tr><th>degree</th>' +
          a.pos.map(function (_, i) { return '<th>' + (i + 1) + '</th>'; }).join('') + '</tr><tr><td>cents</td>' +
          a.pos.map(function (p, i) { return '<td>' + fmtDev(b.pos[i] - p) + '</td>'; }).join('') + '</tr></table>';
      }
      stage.innerHTML = html;
      bindTips(stage);
    }

    function playScale(s, t0, withDrone) {
      var pos = s.pos.slice();
      if (Math.abs(s.span - pos[pos.length - 1]) > 1) pos.push(s.span);
      var step = 0.55, end = t0 + pos.length * step + 0.6;
      if (withDrone) { tone(freq(0), t0, end - t0, 'sine', 0.12); tone(freq(702), t0, end - t0, 'sine', 0.05); }
      pos.forEach(function (p, i) { tone(freq(p), t0 + i * step, 0.7, 'triangle', 0.28); });
      return end;
    }
    function playIds(ids) {
      stopAll(); audio(); newBus();
      var dr = root.querySelector('#dr'), withD = dr ? dr.checked : true, t = ctx.currentTime + 0.1;
      ids.forEach(function (id) { t = playScale(byId[id], t, withD) + 0.1; });
      timers.push(setTimeout(stopAll, (t - ctx.currentTime) * 1000 + 300));
    }

    root.querySelector('#pick').addEventListener('change', function (e) {
      var v = e.target.value, i = selScales.indexOf(v);
      if (e.target.checked && i < 0) selScales.push(v);
      if (!e.target.checked && i >= 0) selScales.splice(i, 1);
      render();
    });
    stage.addEventListener('click', function (e) {
      var b = e.target.closest('button'); if (!b) return;
      if (b.dataset.play) playIds([b.dataset.play]);
      else if (b.dataset.act === 'all') playIds(selScales.slice());
      else if (b.dataset.act === 'stop') stopAll();
    });
    render();
  }

  /* ================= INTERVAL ATLAS ================= */
  var atlasOff = {};
  function atlasView(root) {
    var cults = [];
    D.atlas.forEach(function (a) { if (cults.indexOf(a.culture) < 0) cults.push(a.culture); });
    root.innerHTML =
      '<div class="subnav">' + subnav('atlas') + '</div>' +
      '<p class="eyebrow">Melody · Lab</p><h1 class="page">Interval Atlas</h1>' +
      '<p class="lede">Every named interval size recorded across the entries, from 0 to 720 cents. Notice the clusters: the same sizes recur in different traditions under different names, and the neutral seconds sit between the piano’s semitone and whole tone. Click ▶ to hear an interval; click a name to open its entry.</p>' +
      '<div class="stage"><div class="filterbar" id="fb"></div><div id="rows"></div>' +
      '<div class="legend"><span>Vertical lines are 12-tone equal-tempered steps (every 100 cents). A bar is a range; a dot is a single value.</span></div></div>';
    var fb = root.querySelector('#fb'), rows = root.querySelector('#rows');
    function drawFilter() {
      fb.innerHTML = cults.map(function (c) {
        return '<button data-c="' + c + '" class="' + (atlasOff[c] ? '' : 'on') + '"><i class="dot" style="background:' + col(c) + '"></i>' + esc(cname(c)) + '</button>';
      }).join('');
    }
    function drawRows() {
      var W = 720, X = function (c) { return 6 + (c / 720) * (W - 12); };
      rows.innerHTML = D.atlas.filter(function (a) { return !atlasOff[a.culture]; }).map(function (a, i) {
        var svg = '<svg viewBox="0 0 ' + W + ' 20">';
        for (var g = 0; g <= 700; g += 100) svg += '<line x1="' + X(g) + '" x2="' + X(g) + '" y1="0" y2="20" stroke="#cdbf9f" stroke-width="1"/>';
        if (a.hi) svg += '<rect x="' + X(a.lo) + '" y="5" width="' + (X(a.hi) - X(a.lo)) + '" height="10" rx="5" fill="' + col(a.culture) + '" opacity=".75"/>';
        else svg += '<circle cx="' + X(a.lo) + '" cy="10" r="6" fill="' + col(a.culture) + '"/>';
        svg += '</svg>';
        var val = a.hi ? Math.round(a.lo) + '–' + Math.round(a.hi) : fmt(a.lo);
        var tipHtml = esc(a.label) + '<br>' + esc(cname(a.culture)) + (a.note ? '<br>' + esc(a.note) : '');
        return '<div class="atlas-row" data-tip="' + tipHtml.replace(/"/g, '&quot;') + '"><div><i class="dot" style="background:' + col(a.culture) + '"></i>' +
          '<a href="#/e/' + a.entry + '">' + esc(a.label) + '</a></div>' + svg +
          '<div class="cv">' + val + ' <button class="btn ghost" data-i="' + i + '" style="padding:0 7px;font-size:.7rem">▶</button></div></div>';
      }).join('');
      bindTips(rows);
    }
    fb.addEventListener('click', function (e) {
      var b = e.target.closest('button'); if (!b) return;
      atlasOff[b.dataset.c] = !atlasOff[b.dataset.c]; drawFilter(); drawRows();
    });
    rows.addEventListener('click', function (e) {
      var b = e.target.closest('button'); if (!b) return;
      var list = D.atlas.filter(function (a) { return !atlasOff[a.culture]; }), a = list[+b.dataset.i];
      var c = a.hi ? (a.lo + a.hi) / 2 : a.lo;
      stopAll(); audio(); newBus();
      var t = ctx.currentTime + 0.05;
      tone(freq(0), t, 0.7, 'triangle', 0.25); tone(freq(c), t + 0.8, 0.7, 'triangle', 0.25);
      tone(freq(0), t + 1.7, 1.2, 'triangle', 0.18); tone(freq(c), t + 1.7, 1.2, 'triangle', 0.18);
      timers.push(setTimeout(stopAll, 3200));
    });
    drawFilter(); drawRows();
  }

  /* ================= CYCLE LAB ================= */
  var selCycles = null, cycleSecs = 6;
  var TYPE_COL = { D: '#8c4a3a', T: '#d1a437', B: '#2f7d86', tali: '#c9483a', khali: '#6f93ab' };

  function cyclesView(root, qs) {
    var all = D.cycles, byId = {};
    all.forEach(function (c) { byId[c.id] = c; });
    if (qs && qs.c) selCycles = qs.c.split(',').filter(function (x) { return byId[x]; }).slice(0, 3);
    if (!selCycles) selCycles = ['son', 'standard'];
    var order = [];
    all.forEach(function (c) { if (order.indexOf(c.culture) < 0) order.push(c.culture); });
    var pick = order.map(function (cu) {
      return '<h3>' + esc(cname(cu)) + '</h3>' + all.filter(function (c) { return c.culture === cu; }).map(function (c) {
        return '<label><input type="checkbox" value="' + c.id + '"' + (selCycles.indexOf(c.id) >= 0 ? ' checked' : '') + '><span>' + esc(c.name) + ' <span style="color:var(--muted)">' + c.n + '</span></span></label>';
      }).join('');
    }).join('');

    root.innerHTML =
      '<div class="subnav">' + subnav('cycles') + '</div>' +
      '<p class="eyebrow">Rhythm · Lab</p><h1 class="page">Cycle Lab</h1>' +
      '<p class="lede">Rhythmic cycles from different traditions drawn as circles and played together. Each selected cycle is stretched to the same duration, so a 12-pulse bell pattern and a 16-pulse clave line up the way a 3:2 or 4:3 relationship would. Pick up to three.</p>' +
      '<div class="lab"><div class="pick" id="pick">' + pick + '</div><div class="stage" id="stage"></div></div>';

    var stage = root.querySelector('#stage');

    function circle(c) {
      var S = 240, cx = S / 2, cy = S / 2, R = 88, n = c.n;
      var ang = function (i) { return (-90 + (i * 360) / n) * Math.PI / 180; };
      var pt = function (i, r) { return [cx + r * Math.cos(ang(i)), cy + r * Math.sin(ang(i))]; };
      var svg = '<svg viewBox="0 0 ' + S + ' ' + S + '" data-cyc="' + c.id + '" style="width:100%;max-width:300px;display:block;margin:0 auto" aria-label="' + esc(c.name) + '">';
      svg += '<circle cx="' + cx + '" cy="' + cy + '" r="' + R + '" fill="none" stroke="#cdbf9f" stroke-width="1.5"/>';
      var gs = 0;
      c.groups.forEach(function (g) {
        var p1 = pt(gs, R - 14), p2 = pt(gs, R + 14);
        svg += '<line x1="' + p1[0] + '" y1="' + p1[1] + '" x2="' + p2[0] + '" y2="' + p2[1] + '" stroke="#8a7a5a" stroke-width="2.2"/>';
        gs += g;
      });
      var strokeAt = {};
      c.strokes.forEach(function (s) { strokeAt[s.i] = s.t; });
      for (var i = 0; i < n; i++) {
        var p = pt(i, R), t = strokeAt[i], r = 4, fill = '#e6dabd', stroke = '#9c9075', sw = 1.5;
        if (t) { r = 9; fill = TYPE_COL[t]; stroke = TYPE_COL[t]; }
        else if (c.beat) { r = 5; fill = '#cdbf9f'; }
        if (c.tali.indexOf(i) >= 0) { r = 9; fill = TYPE_COL.tali; stroke = TYPE_COL.tali; }
        if (c.khali.indexOf(i) >= 0) { r = 9; fill = 'none'; stroke = TYPE_COL.khali; sw = 3; }
        svg += '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + r + '" fill="' + fill + '" stroke="' + stroke + '" stroke-width="' + sw + '" data-p="' + i + '"/>';
        if (n <= 16) { var lp = pt(i, R + 26); svg += '<text x="' + lp[0] + '" y="' + (lp[1] + 3) + '" text-anchor="middle" font-size="8.5" fill="#6b5f4e">' + (i + 1) + '</text>'; }
      }
      svg += '<line class="hand" x1="' + cx + '" y1="' + cy + '" x2="' + cx + '" y2="' + (cy - R) + '" stroke="#c9483a" stroke-width="2" opacity="0"/>';
      svg += '<text x="' + cx + '" y="' + (cy + 4) + '" text-anchor="middle" font-size="16" font-family="Fraunces,serif" fill="#2b2118">' + n + '</text>';
      return svg + '</svg>';
    }

    function render() {
      var chosen = selCycles.map(function (id) { return byId[id]; }).filter(Boolean);
      if (!chosen.length) { stage.innerHTML = '<p class="hint">Pick a cycle on the left.</p>'; return; }
      var html = '<h2>' + chosen.length + ' selected</h2>' +
        '<div class="btnrow"><button class="btn" data-act="play">▶ Play together</button><button class="btn ghost" data-act="stop">Stop</button>' +
        '<label style="font-size:.85rem">cycle length <input type="range" id="spd" min="2" max="14" step="0.5" value="' + cycleSecs + '"> <span id="spdv">' + cycleSecs + ' s</span></label></div>' +
        '<div class="legend"><span><i style="background:' + TYPE_COL.D + '"></i>dum / düm (low)</span><span><i style="background:' + TYPE_COL.T + '"></i>tak / tek (high)</span><span><i style="background:' + TYPE_COL.B + '"></i>bell / clave stroke</span><span><i style="background:' + TYPE_COL.tali + '"></i>tali (clap)</span><span><i style="background:none;border:2px solid ' + TYPE_COL.khali + '"></i>khali (wave)</span><span>Bars across the ring mark group boundaries.</span></div>' +
        '<div class="cyc-grid">' + chosen.map(function (c) {
          return '<div class="cyc"><h4><i class="dot" style="background:' + col(c.culture) + '"></i>' + esc(c.name) + '</h4><div class="cn">' + esc(c.note) + '</div>' + circle(c) +
            '<div style="font-size:.76rem;margin-top:4px">' + (c.groups.length ? 'grouping ' + c.groups.join('+') + ' · ' : '') + link(c.entry, 'source entry') + '</div></div>';
        }).join('') + '</div>' +
        (chosen.length > 1 ? '<p class="hint" style="margin-top:12px">All cycles are stretched to the same length. Cycles whose pulse counts share a factor (12 and 16 share 4, for instance) line up on the common beat.</p>' : '');
      stage.innerHTML = html;
    }

    function play() {
      stopAll(); audio(); newBus();
      var chosen = selCycles.map(function (id) { return byId[id]; }).filter(Boolean);
      if (!chosen.length) return;
      var T = cycleSecs, start = ctx.currentTime + 0.15, next = chosen.map(function () { return 0; });
      var svgs = {};
      stage.querySelectorAll('svg[data-cyc]').forEach(function (s) { svgs[s.getAttribute('data-cyc')] = s; });
      function fire(c, i, t) {
        var st = null;
        c.strokes.forEach(function (s) { if (s.i === i) st = s.t; });
        if (st === 'D') thump(t);
        else if (st === 'T') tone(900, t, 0.06, 'square', 0.1);
        else if (st === 'B') tone(1400, t, 0.35, 'triangle', 0.22);
        if (c.tali.indexOf(i) >= 0) noiseBurst(t, 0.07, 0.4, 1700);
        if (c.khali.indexOf(i) >= 0) tone(620, t, 0.14, 'sine', 0.14);
        if (c.beat && !st && c.tali.indexOf(i) < 0 && c.khali.indexOf(i) < 0) {
          var gs = 0, isG = false;
          c.groups.forEach(function (g) { if (gs === i) isG = true; gs += g; });
          tone(isG ? 1500 : 1000, t, 0.03, 'sine', isG ? 0.12 : 0.05);
        }
      }
      function sched() {
        var now = ctx.currentTime;
        chosen.forEach(function (c, k) {
          var dt = T / c.n;
          while (start + next[k] * dt < now + 0.25) {
            fire(c, next[k] % c.n, start + next[k] * dt);
            next[k]++;
          }
        });
      }
      sched();
      timers.push(setInterval(sched, 60));
      function frame() {
        var el = ctx.currentTime - start;
        chosen.forEach(function (c) {
          var s = svgs[c.id]; if (!s) return;
          var h = s.querySelector('.hand'); if (!h) return;
          var frac = el > 0 ? ((el / T) % 1) : 0, a = -Math.PI / 2 + frac * 2 * Math.PI;
          h.setAttribute('x2', 120 + 88 * Math.cos(a)); h.setAttribute('y2', 120 + 88 * Math.sin(a)); h.setAttribute('opacity', '.9');
        });
        raf = requestAnimationFrame(frame);
      }
      raf = requestAnimationFrame(frame);
      onStop = function () { stage.querySelectorAll('.hand').forEach(function (h) { h.setAttribute('opacity', '0'); }); };
    }

    root.querySelector('#pick').addEventListener('change', function (e) {
      var v = e.target.value, i = selCycles.indexOf(v);
      if (e.target.checked) {
        if (i < 0) selCycles.push(v);
        if (selCycles.length > 3) { var drop = selCycles.shift(); var cb = root.querySelector('#pick input[value="' + drop + '"]'); if (cb) cb.checked = false; }
      } else if (i >= 0) selCycles.splice(i, 1);
      stopAll(); render();
    });
    stage.addEventListener('click', function (e) {
      var b = e.target.closest('button'); if (!b) return;
      if (b.dataset.act === 'play') play(); else if (b.dataset.act === 'stop') stopAll();
    });
    stage.addEventListener('input', function (e) {
      if (e.target.id === 'spd') { cycleSecs = +e.target.value; stage.querySelector('#spdv').textContent = cycleSecs + ' s'; }
    });
    render();
  }

  function subnav(on) {
    return [['scales', 'Scale Lab'], ['atlas', 'Interval Atlas'], ['cycles', 'Cycle Lab']].map(function (x) {
      return '<a href="#/lab/' + x[0] + '"' + (on === x[0] ? ' class="on"' : '') + '>' + x[1] + '</a>';
    }).join('');
  }


  /* ---- helpers used by the "Play it" panels (js/play.js) ---- */
  var extraStops = [];
  function stopEverything() { extraStops.forEach(function (f) { try { f(); } catch (e) {} }); extraStops = []; stopAll(); }
  function playCents(list, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var step = opts.step || 0.5, t0 = ctx.currentTime + 0.08, f0 = opts.f0 || 261.63;
    var seq = list.slice();
    if (opts.updown) seq = seq.concat(list.slice(0, -1).reverse());
    var end = t0 + seq.length * step + 0.5;
    if (opts.drone !== false) { tone(f0, t0, end - t0, 'sine', 0.1); tone(f0 * 1.5, t0, end - t0, 'sine', 0.04); }
    seq.forEach(function (c, i) { tone(f0 * Math.pow(2, c / 1200), t0 + i * step, step * 1.3, 'triangle', 0.26); });
    timers.push(setTimeout(stopAll, (end - ctx.currentTime) * 1000 + 300));
  }
  function playPattern(tokens, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var dt = 60 / (opts.bpm || 120) / (opts.sub || 2), loops = opts.loops || 3, t0 = ctx.currentTime + 0.1;
    for (var L = 0; L < loops; L++) {
      tokens.forEach(function (tk, i) {
        var t = t0 + (L * tokens.length + i) * dt;
        if (opts.click && i % (opts.sub || 2) === 0) tone(i === 0 ? 1600 : 1100, t, 0.025, 'sine', 0.05);
        if (tk === 'D') thump(t);
        else if (tk === 'T' || tk === 'K') tone(tk === 'K' ? 700 : 900, t, 0.06, 'square', tk === 'K' ? 0.06 : 0.1);
        else if (tk === 'B') tone(1400, t, 0.3, 'triangle', 0.22);
        else if (tk === 'C') noiseBurst(t, 0.07, 0.4, 1700);
        else if (tk === 'W') tone(620, t, 0.14, 'sine', 0.14);
        else if (tk === 'x') tone(1000, t, 0.03, 'sine', 0.07);
        else if (tk === 'X') tone(1500, t, 0.04, 'sine', 0.14);
      });
    }
    var end = t0 + loops * tokens.length * dt;
    timers.push(setTimeout(stopAll, (end - ctx.currentTime) * 1000 + 400));
  }
  function playContour(points, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var f0 = opts.f0 || 261.63, t0 = ctx.currentTime + 0.08, o = ctx.createOscillator(), g = ctx.createGain();
    o.type = 'triangle';
    var last = points[points.length - 1][0];
    o.frequency.setValueAtTime(f0 * Math.pow(2, points[0][1] / 1200), t0);
    points.forEach(function (p) { o.frequency.linearRampToValueAtTime(f0 * Math.pow(2, p[1] / 1200), t0 + p[0]); });
    g.gain.setValueAtTime(0.0001, t0); g.gain.exponentialRampToValueAtTime(0.25, t0 + 0.04);
    g.gain.setValueAtTime(0.25, t0 + last); g.gain.exponentialRampToValueAtTime(0.0001, t0 + last + 0.3);
    o.connect(g); g.connect(bus); o.start(t0); o.stop(t0 + last + 0.4);
    if (opts.drone !== false) tone(f0, t0, last + 0.4, 'sine', 0.08);
    timers.push(setTimeout(stopAll, (last + 0.8) * 1000));
  }
  function strum(freqs, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var t0 = ctx.currentTime + 0.05;
    freqs.forEach(function (f, i) { tone(f, t0 + i * 0.035, 1.8, 'triangle', 0.16); });
    timers.push(setTimeout(stopAll, 2400));
  }

  window.Labs = { scales: scalesView, atlas: atlasView, cycles: cyclesView, stop: stopEverything,
    playCents: playCents, playPattern: playPattern, strum: strum, playContour: playContour, audio: audio,
    onStop: function (f) { extraStops.push(f); } };
})();
