/* Audio helpers for the lesson blocks, and the Groove Lab (rhythm cycles from
   different traditions played together). Cycle data comes from
   window.LESSONS.cycles (generated by tools/build_lessons.py, each pattern
   from a knowledge-base entry); this file only draws and sounds it. */
(function () {
  'use strict';
  var D = window.LESSONS;
  var CUL = {};
  D.courses.forEach(function (c) { CUL[c.id] = c; });

  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]; }); }
  function col(id) { return (CUL[id] || {}).color || '#b8863b'; }
  function cname(id) { return (CUL[id] || {}).name || id; }

  /* ---------------- audio ---------------- */
  var ctx = null, bus = null, timers = [], raf = 0, onStop = null;
  function audio() {
    if (!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)();
    if (ctx.state === 'suspended') ctx.resume();
    return ctx;
  }
  function newBus() {
    var c = audio();
    bus = c.createGain();
    bus.gain.value = 0.9;
    bus.connect(c.destination);
    return bus;
  }
  function stopAll() {
    timers.forEach(function (t) { clearTimeout(t); clearInterval(t); });
    timers = [];
    if (raf) { cancelAnimationFrame(raf); raf = 0; }
    if (bus && ctx) {
      var b = bus; bus = null;
      try { b.gain.setTargetAtTime(0, ctx.currentTime, 0.03); } catch (e) {}
      setTimeout(function () { try { b.disconnect(); } catch (e) {} }, 200);
    }
    if (onStop) { var f = onStop; onStop = null; f(); }
  }
  function tone(freq, t, dur, type, gain, dest) {
    var c = ctx, o = c.createOscillator(), g = c.createGain();
    o.type = type || 'triangle';
    o.frequency.setValueAtTime(freq, t);
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(gain || 0.25, t + 0.015);
    g.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    o.connect(g); g.connect(dest || bus);
    o.start(t); o.stop(t + dur + 0.05);
  }
  function noiseBurst(t, dur, gain, f) {
    var c = ctx, n = Math.max(1, Math.floor(c.sampleRate * dur)), buf = c.createBuffer(1, n, c.sampleRate), d = buf.getChannelData(0);
    for (var i = 0; i < n; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / n);
    var s = c.createBufferSource(), bp = c.createBiquadFilter(), g = c.createGain();
    s.buffer = buf; bp.type = 'bandpass'; bp.frequency.value = f || 1800; bp.Q.value = 0.8;
    g.gain.value = gain || 0.3;
    s.connect(bp); bp.connect(g); g.connect(bus); s.start(t);
  }
  function thump(t) {
    var c = ctx, o = c.createOscillator(), g = c.createGain();
    o.type = 'sine';
    o.frequency.setValueAtTime(150, t); o.frequency.exponentialRampToValueAtTime(70, t + 0.12);
    g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(0.7, t + 0.01); g.gain.exponentialRampToValueAtTime(0.0001, t + 0.3);
    o.connect(g); g.connect(bus); o.start(t); o.stop(t + 0.35);
  }
  /* ================= GROOVE LAB ================= */
  var selCycles = null, cycleSecs = 6;
  var TYPE_COL = { D: '#8c4a3a', T: '#d1a437', B: '#2f7d86', tali: '#c9483a', khali: '#6f93ab' };

  function cyclesView(root, qs) {
    var all = D.cycles, byId = {};
    all.forEach(function (c) { byId[c.id] = c; });
    if (qs && qs.c) selCycles = qs.c.split(',').filter(function (x) { return byId[x]; }).slice(0, 3);
    if (!selCycles) selCycles = ['son', 'standard'];
    var order = [];
    all.forEach(function (c) { if (order.indexOf(c.culture) < 0) order.push(c.culture); });
    var pick = order.map(function (cu) {
      return '<h3>' + esc(cname(cu)) + '</h3>' + all.filter(function (c) { return c.culture === cu; }).map(function (c) {
        return '<label><input type="checkbox" value="' + c.id + '"' + (selCycles.indexOf(c.id) >= 0 ? ' checked' : '') + '><span>' + esc(c.name) + ' <span style="color:var(--muted)">' + c.n + '</span></span></label>';
      }).join('');
    }).join('');

    root.innerHTML =
      '<p class="eyebrow">Practice tool</p><h1 class="page">Groove Lab</h1>' +
      '<p class="lede">Play grooves from different traditions together and practise over them. Each cycle is drawn as a circle; pick up to three and they are stretched to the same length, so a 12-pulse bell and a 16-pulse clave line up the way 3 against 4 does. Set the cycle length, press play, and comp or solo on top.</p>' +
      '<div class="lab"><div class="pick" id="pick">' + pick + '</div><div class="stage" id="stage"></div></div>';

    var stage = root.querySelector('#stage');

    function circle(c) {
      var S = 240, cx = S / 2, cy = S / 2, R = 88, n = c.n;
      var ang = function (i) { return (-90 + (i * 360) / n) * Math.PI / 180; };
      var pt = function (i, r) { return [cx + r * Math.cos(ang(i)), cy + r * Math.sin(ang(i))]; };
      var svg = '<svg viewBox="0 0 ' + S + ' ' + S + '" data-cyc="' + c.id + '" style="width:100%;max-width:300px;display:block;margin:0 auto" aria-label="' + esc(c.name) + '">';
      svg += '<circle cx="' + cx + '" cy="' + cy + '" r="' + R + '" fill="none" stroke="#cdbf9f" stroke-width="1.5"/>';
      var gs = 0;
      c.groups.forEach(function (g) {
        var p1 = pt(gs, R - 14), p2 = pt(gs, R + 14);
        svg += '<line x1="' + p1[0] + '" y1="' + p1[1] + '" x2="' + p2[0] + '" y2="' + p2[1] + '" stroke="#8a7a5a" stroke-width="2.2"/>';
        gs += g;
      });
      var strokeAt = {};
      c.strokes.forEach(function (s) { strokeAt[s.i] = s.t; });
      for (var i = 0; i < n; i++) {
        var p = pt(i, R), t = strokeAt[i], r = 4, fill = '#e6dabd', stroke = '#9c9075', sw = 1.5;
        if (t) { r = 9; fill = TYPE_COL[t]; stroke = TYPE_COL[t]; }
        else if (c.beat) { r = 5; fill = '#cdbf9f'; }
        if (c.tali.indexOf(i) >= 0) { r = 9; fill = TYPE_COL.tali; stroke = TYPE_COL.tali; }
        if (c.khali.indexOf(i) >= 0) { r = 9; fill = 'none'; stroke = TYPE_COL.khali; sw = 3; }
        svg += '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + r + '" fill="' + fill + '" stroke="' + stroke + '" stroke-width="' + sw + '" data-p="' + i + '"/>';
        if (n <= 16) { var lp = pt(i, R + 26); svg += '<text x="' + lp[0] + '" y="' + (lp[1] + 3) + '" text-anchor="middle" font-size="8.5" fill="#6b5f4e">' + (i + 1) + '</text>'; }
      }
      svg += '<line class="hand" x1="' + cx + '" y1="' + cy + '" x2="' + cx + '" y2="' + (cy - R) + '" stroke="#c9483a" stroke-width="2" opacity="0"/>';
      svg += '<text x="' + cx + '" y="' + (cy + 4) + '" text-anchor="middle" font-size="16" font-family="Fraunces,serif" fill="#2b2118">' + n + '</text>';
      return svg + '</svg>';
    }

    function render() {
      var chosen = selCycles.map(function (id) { return byId[id]; }).filter(Boolean);
      if (!chosen.length) { stage.innerHTML = '<p class="hint">Pick a cycle on the left.</p>'; return; }
      var html = '<h2>' + chosen.length + ' selected</h2>' +
        '<div class="btnrow"><button class="btn" data-act="play">▶ Play together</button><button class="btn ghost" data-act="stop">Stop</button>' +
        '<label style="font-size:.85rem">cycle length <input type="range" id="spd" min="2" max="14" step="0.5" value="' + cycleSecs + '"> <span id="spdv">' + cycleSecs + ' s</span></label></div>' +
        '<div class="legend"><span><i style="background:' + TYPE_COL.D + '"></i>dum / düm (low)</span><span><i style="background:' + TYPE_COL.T + '"></i>tak / tek (high)</span><span><i style="background:' + TYPE_COL.B + '"></i>bell / clave stroke</span><span><i style="background:' + TYPE_COL.tali + '"></i>tali (clap)</span><span><i style="background:none;border:2px solid ' + TYPE_COL.khali + '"></i>khali (wave)</span><span>Bars across the ring mark group boundaries.</span></div>' +
        '<div class="cyc-grid">' + chosen.map(function (c) {
          return '<div class="cyc"><h4><i class="dot" style="background:' + col(c.culture) + '"></i>' + esc(c.name) + '</h4><div class="cn">' + esc(c.note) + '</div>' + circle(c) +
            '<div style="font-size:.76rem;margin-top:4px">' + (c.groups.length ? 'grouping ' + c.groups.join('+') + ' · ' : '') + '<a href="#/lesson/' + c.lesson + '">learn it</a></div></div>';
        }).join('') + '</div>' +
        (chosen.length > 1 ? '<p class="hint" style="margin-top:12px">All cycles are stretched to the same length. Cycles whose pulse counts share a factor (12 and 16 share 4, for instance) line up on the common beat.</p>' : '');
      stage.innerHTML = html;
    }

    function play() {
      stopAll(); audio(); newBus();
      var chosen = selCycles.map(function (id) { return byId[id]; }).filter(Boolean);
      if (!chosen.length) return;
      var T = cycleSecs, start = ctx.currentTime + 0.15, next = chosen.map(function () { return 0; });
      var svgs = {};
      stage.querySelectorAll('svg[data-cyc]').forEach(function (s) { svgs[s.getAttribute('data-cyc')] = s; });
      function fire(c, i, t) {
        var st = null;
        c.strokes.forEach(function (s) { if (s.i === i) st = s.t; });
        if (st === 'D') thump(t);
        else if (st === 'T') tone(900, t, 0.06, 'square', 0.1);
        else if (st === 'B') tone(1400, t, 0.35, 'triangle', 0.22);
        if (c.tali.indexOf(i) >= 0) noiseBurst(t, 0.07, 0.4, 1700);
        if (c.khali.indexOf(i) >= 0) tone(620, t, 0.14, 'sine', 0.14);
        if (c.beat && !st && c.tali.indexOf(i) < 0 && c.khali.indexOf(i) < 0) {
          var gs = 0, isG = false;
          c.groups.forEach(function (g) { if (gs === i) isG = true; gs += g; });
          tone(isG ? 1500 : 1000, t, 0.03, 'sine', isG ? 0.12 : 0.05);
        }
      }
      function sched() {
        var now = ctx.currentTime;
        chosen.forEach(function (c, k) {
          var dt = T / c.n;
          while (start + next[k] * dt < now + 0.25) {
            fire(c, next[k] % c.n, start + next[k] * dt);
            next[k]++;
          }
        });
      }
      sched();
      timers.push(setInterval(sched, 60));
      function frame() {
        var el = ctx.currentTime - start;
        chosen.forEach(function (c) {
          var s = svgs[c.id]; if (!s) return;
          var h = s.querySelector('.hand'); if (!h) return;
          var frac = el > 0 ? ((el / T) % 1) : 0, a = -Math.PI / 2 + frac * 2 * Math.PI;
          h.setAttribute('x2', 120 + 88 * Math.cos(a)); h.setAttribute('y2', 120 + 88 * Math.sin(a)); h.setAttribute('opacity', '.9');
        });
        raf = requestAnimationFrame(frame);
      }
      raf = requestAnimationFrame(frame);
      onStop = function () { stage.querySelectorAll('.hand').forEach(function (h) { h.setAttribute('opacity', '0'); }); };
    }

    root.querySelector('#pick').addEventListener('change', function (e) {
      var v = e.target.value, i = selCycles.indexOf(v);
      if (e.target.checked) {
        if (i < 0) selCycles.push(v);
        if (selCycles.length > 3) { var drop = selCycles.shift(); var cb = root.querySelector('#pick input[value="' + drop + '"]'); if (cb) cb.checked = false; }
      } else if (i >= 0) selCycles.splice(i, 1);
      stopAll(); render();
    });
    stage.addEventListener('click', function (e) {
      var b = e.target.closest('button'); if (!b) return;
      if (b.dataset.act === 'play') play(); else if (b.dataset.act === 'stop') stopAll();
    });
    stage.addEventListener('input', function (e) {
      if (e.target.id === 'spd') { cycleSecs = +e.target.value; stage.querySelector('#spdv').textContent = cycleSecs + ' s'; }
    });
    render();
  }

  /* ---- helpers used by the lesson blocks (js/play.js) ---- */
  var extraStops = [];
  function stopEverything() { extraStops.forEach(function (f) { try { f(); } catch (e) {} }); extraStops = []; stopAll(); }
  function playCents(list, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var step = opts.step || 0.5, t0 = ctx.currentTime + 0.08, f0 = opts.f0 || 261.63;
    var seq = list.slice();
    if (opts.updown) seq = seq.concat(list.slice(0, -1).reverse());
    var end = t0 + seq.length * step + 0.5;
    if (opts.drone !== false) { tone(f0, t0, end - t0, 'sine', 0.1); tone(f0 * 1.5, t0, end - t0, 'sine', 0.04); }
    seq.forEach(function (c, i) { tone(f0 * Math.pow(2, c / 1200), t0 + i * step, step * 1.3, 'triangle', 0.26); });
    timers.push(setTimeout(stopAll, (end - ctx.currentTime) * 1000 + 300));
  }
  function playPattern(tokens, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var dt = 60 / (opts.bpm || 120) / (opts.sub || 2), loops = opts.loops || 3, t0 = ctx.currentTime + 0.1;
    for (var L = 0; L < loops; L++) {
      tokens.forEach(function (tk, i) {
        var t = t0 + (L * tokens.length + i) * dt;
        if (opts.click && i % (opts.sub || 2) === 0) tone(i === 0 ? 1600 : 1100, t, 0.025, 'sine', 0.05);
        if (tk === 'D') thump(t);
        else if (tk === 'T' || tk === 'K') tone(tk === 'K' ? 700 : 900, t, 0.06, 'square', tk === 'K' ? 0.06 : 0.1);
        else if (tk === 'B') tone(1400, t, 0.3, 'triangle', 0.22);
        else if (tk === 'C') noiseBurst(t, 0.07, 0.4, 1700);
        else if (tk === 'W') tone(620, t, 0.14, 'sine', 0.14);
        else if (tk === 'x') tone(1000, t, 0.03, 'sine', 0.07);
        else if (tk === 'X') tone(1500, t, 0.04, 'sine', 0.14);
      });
    }
    var end = t0 + loops * tokens.length * dt;
    timers.push(setTimeout(stopAll, (end - ctx.currentTime) * 1000 + 400));
  }
  function playContour(points, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var f0 = opts.f0 || 261.63, t0 = ctx.currentTime + 0.08, o = ctx.createOscillator(), g = ctx.createGain();
    o.type = 'triangle';
    var last = points[points.length - 1][0];
    o.frequency.setValueAtTime(f0 * Math.pow(2, points[0][1] / 1200), t0);
    points.forEach(function (p) { o.frequency.linearRampToValueAtTime(f0 * Math.pow(2, p[1] / 1200), t0 + p[0]); });
    g.gain.setValueAtTime(0.0001, t0); g.gain.exponentialRampToValueAtTime(0.25, t0 + 0.04);
    g.gain.setValueAtTime(0.25, t0 + last); g.gain.exponentialRampToValueAtTime(0.0001, t0 + last + 0.3);
    o.connect(g); g.connect(bus); o.start(t0); o.stop(t0 + last + 0.4);
    if (opts.drone !== false) tone(f0, t0, last + 0.4, 'sine', 0.08);
    timers.push(setTimeout(stopAll, (last + 0.8) * 1000));
  }
  function strum(freqs, opts) {
    opts = opts || {};
    stopEverything(); audio(); newBus();
    var t0 = ctx.currentTime + 0.05;
    freqs.forEach(function (f, i) { tone(f, t0 + i * 0.035, 1.8, 'triangle', 0.16); });
    timers.push(setTimeout(stopAll, 2400));
  }

  window.Labs = { grooves: cyclesView, stop: stopEverything,
    playCents: playCents, playPattern: playPattern, strum: strum, playContour: playContour, audio: audio,
    onStop: function (f) { extraStops.push(f); } };
})();
